[2021-10-10 17:04:16,417] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: example_subdag_operator.section-1 2021-10-08T00:00:00+00:00 [queued]>
[2021-10-10 17:04:16,423] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: example_subdag_operator.section-1 2021-10-08T00:00:00+00:00 [queued]>
[2021-10-10 17:04:16,423] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2021-10-10 17:04:16,423] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2021-10-10 17:04:16,423] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2021-10-10 17:04:16,431] {taskinstance.py:1115} INFO - Executing <Task(SubDagOperator): section-1> on 2021-10-08T00:00:00+00:00
[2021-10-10 17:04:16,433] {standard_task_runner.py:52} INFO - Started process 15377 to run task
[2021-10-10 17:04:16,436] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'example_subdag_operator', 'section-1', '2021-10-08T00:00:00+00:00', '--job-id', '32', '--pool', 'default_pool', '--raw', '--subdir', '/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_subdag_operator.py', '--cfg-path', '/tmp/tmpbhwldd4o', '--error-file', '/tmp/tmp3u9kkaao']
[2021-10-10 17:04:16,437] {standard_task_runner.py:77} INFO - Job 32: Subtask section-1
[2021-10-10 17:04:16,516] {logging_mixin.py:109} INFO - Running <TaskInstance: example_subdag_operator.section-1 2021-10-08T00:00:00+00:00 [running]> on host abd
[2021-10-10 17:04:16,545] {taskinstance.py:1252} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_subdag_operator
AIRFLOW_CTX_TASK_ID=section-1
AIRFLOW_CTX_EXECUTION_DATE=2021-10-08T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-08T00:00:00+00:00
[2021-10-10 17:04:16,560] {subdag.py:155} INFO - Created DagRun: scheduled__2021-10-08T00:00:00+00:00
[2021-10-10 17:05:54,215] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 15377
[2021-10-10 17:05:54,215] {taskinstance.py:1236} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-10-10 17:05:54,219] {taskinstance.py:1463} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/taskinstance.py", line 1165, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/taskinstance.py", line 1283, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/taskinstance.py", line 1313, in _execute_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.8/dist-packages/airflow/sensors/base.py", line 246, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/taskinstance.py", line 1238, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-10-10 17:05:54,221] {taskinstance.py:1506} INFO - Marking task as FAILED. dag_id=example_subdag_operator, task_id=section-1, execution_date=20211008T000000, start_date=20211010T140416, end_date=20211010T140554
[2021-10-10 17:05:54,269] {process_utils.py:66} INFO - Process psutil.Process(pid=15377, status='terminated', exitcode=1, started='17:04:15') (15377) terminated with exit code 1
